# Generated by Django 4.0.3 on 2023-04-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_alter_donor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='otp',
            field=models.CharField(default='0000', max_length=25),
        ),
    ]
