# Generated by Django 4.0.3 on 2023-04-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_donor_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
