# Generated by Django 4.0.3 on 2023-04-18 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_donor_password_alter_blooddonate_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='hemoglobin',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(12.5)]),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='blooddonate',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
