# Generated by Django 4.0.3 on 2023-04-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0012_alter_donor_last_donation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='last_donation_date',
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
