# Generated by Django 4.0.3 on 2023-04-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0018_remove_donor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
