# Generated by Django 4.0.3 on 2023-04-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0019_alter_donor_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='User_Stock',
        ),
    ]
