# Generated by Django 4.0.3 on 2023-05-04 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0020_rename_stock_user_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)]),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(45)]),
        ),
    ]
