# Generated by Django 4.0.3 on 2023-05-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0021_alter_blooddonate_age_alter_blooddonate_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
