# Generated by Django 4.0.3 on 2023-05-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_alter_bloodrequest_requisition_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
