# Generated by Django 4.0.3 on 2023-05-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_email_delete_replyform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_by_patient',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='requisition_form',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
