# Generated by Django 4.0.3 on 2023-05-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_bloodrequest_request_by_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='requisition_form',
            field=models.ImageField(blank=True, null=True, upload_to='image/Req_form'),
        ),
    ]
